version: "3.8"

services:
  django_app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: poetry run python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  dramatiq_worker:
    build: .
    volumes:
      - .:/app
    command: poetry run python manage.py rundramatiq
    depends_on:
      - redis

  telegram_bot:
    build: .
    volumes:
      - .:/app
    command: poetry run python manage.py runbot
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
